# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ML Learning Initiative
description: > # this means to ignore newlines until "baseurl:"

baseurl: "/Phantom-Jekyll-Theme" # the subpath of your site, e.g. /blog
url: "http://bcasal.github.io" # the base hostname & protocol for your site

# Contact settings
email: your-email@domain.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdowm: kramdown

kramdown:
  input:      GFM
  auto_ids:   false

exclude: ["README.md", "LICENSE.md", "screenshot.png"]
